name: Deploy Managed Solution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch, release(tag)
  # Workflow_dispatch para rodar manualmente pelo actions passando os parametros
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: SolucaoTeste
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/export/
      solution_source_folder:
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/
      solution_release_folder:
       description: 'folder where the released binaries are going to be hosted *do not change*'
       required: true
       default: out/release
  release:
    types: [created]
    
env:
#edit your values here
  ORIGEM_ENVIRONMENT_URL: 'https://orga259a2b4.crm2.dynamics.com'
  DESTINO_ENVIRONMENT_URL: 'https://org86768755.crm2.dynamics.com/'
  ORIGEM_USERNAME: 'admin@almdestino.onmicrosoft.com'
  DESTINO_USERNAME: 'admin@almorigem.onmicrosoft.com'
  PASSWORD: ${{secrets.PASSWORD}}

jobs:
  #Nome do Job, pode ter mais de um
  export-solution-origem-env:

    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest

    steps:
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ORIGEM_ENVIRONMENT_URL}}
        user-name: ${{ env.ORIGEM_USERNAME }}
        password-secret: ${{ env.PASSWORD }}
    
    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ORIGEM_ENVIRONMENT_URL}}
        user-name: ${{ env.ORIGEM_USERNAME }}
        password-secret: ${{ env.PASSWORD }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        managed: true

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip


  release-to-another-env:
      needs: [ export-solution-origem-env ]
      runs-on: windows-latest
      env:
        RUNNER_DEBUG: 1

      steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Fetch the ready to ship solution from GH artifact store
        uses: actions/download-artifact@v2
        with:
          name: managedSolutions
          path: out/release/

      - name: Import solution to destino env
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{env.DESTINO_ENVIRONMENT_URL}}
          user-name: ${{ env.DESTINO_USERNAME }}
          password-secret: ${{ env.PASSWORD }}
          solution-file: ${{ github.event.inputs.solution_release_folder}}/${{ github.event.inputs.solution_name}}.zip
          force-overwrite: true
          publish-changes: true
